#!/bin/bash

Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_aa_line_count_adjusted.txt dhyper_output_aa.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ab_line_count_adjusted.txt dhyper_output_ab.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ac_line_count_adjusted.txt dhyper_output_ac.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ad_line_count_adjusted.txt dhyper_output_ad.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ae_line_count_adjusted.txt dhyper_output_ae.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_af_line_count_adjusted.txt dhyper_output_af.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ag_line_count_adjusted.txt dhyper_output_ag.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ah_line_count_adjusted.txt dhyper_output_ah.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ai_line_count_adjusted.txt dhyper_output_ai.txt
Rscript do_dhyper.R 20001 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_aj_line_count_adjusted.txt dhyper_output_aj.txt
Rscript do_dhyper.R 15276 HYPERGEOMETRIC_RATIO_TEST_INPUT_FILE_for_all_studies_ak_line_count_adjusted.txt dhyper_output_ak.txt

